Numpy is a fundamental libary for scientific computing in python . It provides support for arrays and matrices , along with collection of mathematical functions to operate on this data structures . Here , we will cover the basic of numpy focusing on arrays and vectorized operations .

In [1]:
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com


In [4]:
import numpy as np


# create arrays as numpy

# create a 1D array 
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
arr2 = np.array([1,2,3,4,5])
print(arr2.shape)
arr2.reshape(1,5)                # 2d array with 1 row and 5 column

(5,)


array([[1, 2, 3, 4, 5]])

In [ ]:
# To keep in mind when re-shape 

# arr2.reshape(1,4) 
# arr2.reshape(2,5) 

# this will give us error

ValueError: cannot reshape array of size 5 into shape (1,4)

how to know the array is 1d,2d or 3d just count the [[[ This ]]]
[] - 1d
[[]] -2d
[[[]]] - 3d

In [ ]:
# 2d array
arr2 = np.array([[1,2,3,4,5]])
print(arr2)
arr2.shape

[[1 2 3 4 5]]


(1, 5)

In [ ]:
# 2d array
arr2 = np.array([[1,2,3,4,5],[5,4,3,2,1]])
print(arr2)
arr2.shape

[[1 2 3 4 5]
 [5 4 3 2 1]]


(2, 5)

In [23]:
# Now array with some inbuilt functions

print(np.arange(0,10))
print(np.arange(2,10,2))

[0 1 2 3 4 5 6 7 8 9]
[2 4 6 8]


In [26]:
arr1 = np.arange(1,10,2).reshape(5,1)
print(arr1)

[[1]
 [3]
 [5]
 [7]
 [9]]


In [27]:
np.arange(1,10,2).reshape(5,1)

array([[1],
       [3],
       [5],
       [7],
       [9]])

In [28]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [34]:
arr = np.array([[1,2,3],[4,5,6]])

print("Array: \n",arr)

print("Shape :" , arr.shape)

print("Number of dimentions : " , arr.ndim)

print("Size(number of elements) :" ,arr.size)

print("Data Type :", arr.dtype)  #(o/p may vary based on the platform)

print("Item size (in bytes) : ",arr.itemsize)  #(o/p may vary based on the platform)

Array: 
 [[1 2 3]
 [4 5 6]]
Shape : (2, 3)
Number of dimentions :  2
Size(number of elements) : 6
Data Type : int64
Item size (in bytes) :  8


In [46]:
# Numpy Vectorize Operation 

arr1 =np.array([1,2,3,4,5])
arr2 =np.array([10,20,30,40,50])

# Elements wise addition
print("Addition :" , arr1 + arr2)

# Elemnts wise substraction
print("Substraction :" , arr2 - arr1)
print("mul :" , arr1 * arr2)
print("div :" , arr2 / arr1)

Addition : [11 22 33 44 55]
Substraction : [ 9 18 27 36 45]
mul : [ 10  40  90 160 250]
div : [10. 10. 10. 10. 10.]


In [ ]:
# Universal Function 
arr = np.array([1,2,3,4,5])

#square root
print(np.sqrt(arr))

#exponential
print(np.exp(arr))     #exponential function e^^x


# e ≈ 2.71828 (Euler’s number, the base of natural logarithms).

# For each element in arr, NumPy calculates e^^value

#sine
print(np.sin(arr))

#natural log   means base is e
print(np.log(arr))

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [49]:
# array slicing and indexing

arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

print("Array : \n" , arr)

print(arr.shape)

Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


In [71]:
# (rows, columns)

# print(arr[0][0])

# print(arr[1:])

# print(arr[1:,2:])


# print - 6 ,7 and 10,11

print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [73]:
# Modify array elemnts
print(arr)
arr[0,0] = 100
print(arr)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [74]:
arr[1:,2:] = 100
print(arr)


[[100   2   3   4]
 [  5   6 100 100]
 [  9  10 100 100]]


In [ ]:
# Stastical Concepts - Normalization
# have a mean of 0 and standard deviation of 1

data = np.array([1,2,3,4,5])

# Calculate the mean and standard deviation

mean = np.mean(data)
std_dev = np.std(data)
print(mean) 
print(std_dev) 

# Normalized the data
normalize_data = (data - mean) / std_dev     # standard normal distribution or standardiation 

print("Normalized data : " , normalize_data)

3.0
1.4142135623730951
Normalized data :  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [ ]:
data = np.arange(1,10)

mean = np.mean(data)
median = np.median(data)
std_dev = np.std(data)
variance = np.var(data)

print(mean,median,std_dev,variance , sep = " :: ") 

5.0 :: 5.0 :: 2.581988897471611 :: 6.666666666666667


In [ ]:
# Logical Operations
data = np.arange(1,11)

print(data)
print(data > 5)
print(data[data > 5])


# print(data[data >= 5  and  data <= 8])

# here and will not work . In numpy & will work and it is overloaded to work with each elemnet of array.
# and will not work as it does not know how to deal with 2d array and all .

print(data[(data >= 5)  & (data <= 8)])

[ 1  2  3  4  5  6  7  8  9 10]
[False False False False False  True  True  True  True  True]
[ 6  7  8  9 10]
[5 6 7 8]
